server:
  http_port: 8080
  host: "0.0.0.0"
  token_exp_minutes: 1440
  refresh_token_exp_minutes: 2880
  token_secret: "P@$$%Secret6677"

db:
  user: "postgres"
  pass: "postgres"
  host: "postgres"  # Use the service name from Docker Compose
  port: 5432
  db_name: "interview"