version: '3.8'

services:
  postgres:
    image: postgres:16.3-bookworm
    container_name: postgres
    environment:
      POSTGRES_DB: interview
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - backend-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: "unless-stopped"
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge

volumes:
  pg-data:
    driver: local